### ISSUE TITLE
Epic: Send Ojo Price Data via Axlear GMP Transactions

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/ojo-evm#3]
This should likely have its own module for governance transactions.

We need to create a override the IBC transaction type on Ojo which allows ojo to pass information from the KV store directly to axelar's GMP.
[Here are the docs for Cosmos -> EVM GMP](https://docs.axelar.dev/dev/general-message-passing/cosmos-gmp).

This transaction should: 
* Take price info from Ojo's KV store and submit it as metadata to the GMP caller.
* Be trustless - anyone can execute this transaction safely.

Here is the current branch: https://github.com/ojo-network/ojo/pull/304

Here are the rest of the TODOs after this branch is merged in:

- [x] https://github.com/ojo-network/ojo/issues/309
- [x] https://github.com/ojo-network/ojo/issues/310
- [x] https://github.com/ojo-network/ojo/issues/311
- [x] https://github.com/ojo-network/ojo/issues/312
- [ ] https://github.com/ojo-network/ojo/issues/313
- [x] #6
- [ ] https://github.com/ojo-network/ojo/issues/316
